//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YPrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fabric_Textile
    {
        public int Party { get; set; }
        public int Roll { get; set; }
        public string Textile_Id { get; set; }
        public double Lenght { get; set; }
    
        public virtual Textile Textile { get; set; }
    }
}
