//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YPrak
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fyr_Type
    {
        public string Fyr_Id { get; set; }
        public int Type_Id { get; set; }
        public int Fyr_Type_Id { get; set; }
    
        public virtual Fyr Fyr { get; set; }
        public virtual Type Type { get; set; }
    }
}
