//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YPrak
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class prak1Entities1 : DbContext
    {
        public prak1Entities1()
            : base("name=prak1Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Color> Color { get; set; }
        public virtual DbSet<Consist> Consist { get; set; }
        public virtual DbSet<Fabric_Fyr> Fabric_Fyr { get; set; }
        public virtual DbSet<Fabric_Textile> Fabric_Textile { get; set; }
        public virtual DbSet<Fyr> Fyr { get; set; }
        public virtual DbSet<Fyr_Product> Fyr_Product { get; set; }
        public virtual DbSet<Fyr_Type> Fyr_Type { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<Ordered_Products> Ordered_Products { get; set; }
        public virtual DbSet<Picture> Picture { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Textile> Textile { get; set; }
        public virtual DbSet<Textile_Color> Textile_Color { get; set; }
        public virtual DbSet<Textile_Consist> Textile_Consist { get; set; }
        public virtual DbSet<Textile_Product> Textile_Product { get; set; }
        public virtual DbSet<Type> Type { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
